create_clock -period 1.600 -name clk -waveform {0.000 0.800} [get_ports clk_in]
create_clock -period 10 -name clk_100 -waveform {0.000 5.000} [get_ports clk_100]
set_false_path -from [get_pins cptphv_reg*/C] -to [get_pins phvBus_reg*/CE]
set_false_path -from [get_pins cptphv_reg*/C] -to [get_pins phvBus_reg*/D]
set_false_path -from [get_pins cptphv_reg*/*] -to [get_pins phvBus_reg*/*]
set_false_path -from [get_pins cptphv_reg*/*] -to [get_pins cptphv_reg*/*]
set_false_path -from [get_clocks clk] -to [get_clocks txoutclk*]
set_false_path -from [get_clocks txoutclk*] -to [get_clocks clk]
set_false_path -from [get_clocks rxoutclk*] -to [get_clocks clk]
